const atletas = [
    {
        nome: "Alan Fonteles Cardoso de Oliveira ",
        esporte: "Atletismo",
        descricao: "O velocista Alan Fonteles Cardoso de Oliveira é campeão paralímpico nos 200 m rasos de Londres 2012, na classificação T44. Na ocasião, o paraense venceu o favorito da prova, o sul-africano Oscar Pistorius. O atleta também é medalha de prata no revezamento 4x100m em Pequim 2008 e na Rio 2016.",
        classificacao: "T62",
        modalidade: "100m e 400m",
        imagem: "https://www.palesttrando.com.br/wp-content/uploads/2019/09/Alan-fonteles-Palesttrando.jpg",
        tags: "atletismo velocista corrida corredor",
    },
    {
        nome: "Alessandro Rodrigo da Silva - Gigante Alê",
        esporte: "Atletismo",
        descricao: "Natural de Santo André (SP), Alessandro se tornou deficiente visual em 2009, após contrair toxoplasmose. Já em 2013, ele conheceu o esporte paralímpico por meio de um ex-professor que o apresentou à prova de arremesso de peso.",
        classificacao: "F11",
        modalidade: "Lançamento de Disco e Arremesso de Peso",
        imagem: "https://s2.glbimg.com/yci5tvqn-W8QsXmViYj86YILaTw=/0x0:4280x2916/690x470/s.glbimg.com/es/ge/f/original/2016/09/12/fmaia_0027.jpg",
        tags: "atletismo velocista corrida corredor",
    },
    {
        nome: "Cássio Lopes dos Reis",
        esporte: "Futebol de Cegos ",
        descricao: "Cássio Lopes dos Reis é um futebolista paralímpico brasileiro, que joga na posição de fixo. Atualmente, atua na seleção brasileira de futebol de 5, exclusiva a deficientes visuais; na qual representou seu país nos Jogos Olímpicos de Verão de 2016, no Rio de Janeiro.",
        classificacao: "B1",
        modalidade: "Masculino",
        imagem: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrugolhGDbf1qQxJ2DsnDbF7vtOc2wCKNT7A&s",
        tags: "futebol para cegos fut ",
    },
    {
        nome: "Ana Gabriely Brito Assunção",
        esporte: "Golbol",
        descricao: "Devido ao albinismo, Ana Gabrielly possui baixa visão. Moradora do Rio de Janeiro, teve seu primeiro contato com o Goalball durante as aulas de Educação Física no Instituto Benjamin Constant. A partir de 2014, começou a se dedicar de forma intensiva a essa modalidade esportiva.",
        classificacao: "B3",
        modalidade: "Feminino",
        imagem: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRH4yy_t-GF5yEVO3ALNKPjvRJyHNu4WbOiTw&s",
        tags: "gol bol goalball ",
    },
    {
        nome: "Alana Martins Maldonado",
        esporte: "Judô",
        descricao: "Descobriu a doença de Stargardt aos 14 anos. Já praticava judô desde os quatro, mas, somente em 2014, quando entrou para a faculdade, começo no judô paralímpico. Líder do ranking mundial de sua categoria.",
        classificacao: "J2",
        modalidade: "Até 70kg",
        imagem: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7sOtdJKioLVavizhzts9le1hnKmGa5As1VA&s",
        tags: "judô judo judoca judoka ",
    },
    {
        nome: "Alan Kleber Basílio",
        esporte: "Natação",
        descricao: "Alan tem uma lesão medular ocasionada por disparo de arma de fogo e que o deixou paraplégico. Começou no esporte paralímpico após assistir aos Jogos Paralímpicos do Rio 2016.",
        classificacao: "S4",
        modalidade: "50m livre, 100m livre e 200m livre",
        imagem: "https://metropolitanoonline.com.br/site/image/data/Esportes/Atleta%20campo-larguense%203009%203%20(1).jpeg",
        tags: "natacao nadador natação",
    },
    {
        nome: "Bruna Costa Alexandre",
        esporte: "Tênis de Mesa",
        descricao: "Aos seis meses de vida, Bruna foi submetida à amputação do braço direito por consequência de uma trombose, provocada por uma injeção mal aplicada. A jovem começou no tênis de mesa aos 12 anos, influenciada pelo irmão. Até 2009, competiu em torneios apenas para atletas sem deficiência. Em 2024, tornou-se a primeira atleta paralímpica brasileira convocada para uma edição de Jogos Olímpicos.",
        classificacao: "Classe 10",
        modalidade: "Feminino",
        imagem: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgoNwjuOFr2njxI4u0csmzJGqJUT-2SDcVqQ&s",
        tags: "tenista tênis tenis mesa pingpong",
    },
    {
        nome: "Gabriel Geraldo dos Santos Araújo (Grabrielzinho)",
        esporte: "Natação",
        descricao: "Gabriel tem focomelia, doença congênita que impede a formação normal de braços e pernas, e conheceu a natação por meio de um professor de Educação Física da escola onde estudava, nos Jogos Escolares de Minas Gerais (JEMG).",
        classificacao: "S2 e SM2",
        modalidade: "50m costas, 100m costas, 150m medley, 50m livre e 200m livre",
        imagem: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJn-ZouVnpvoESfTUi4NP2BvUSExaXCBvQOg&s",
        tags: "natacao nadador natação"
    },
];
